sudo: required

dist: trusty

branches:
  only:
    - master
    - next
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

before_install:
  - export TZ=Europe/Berlin
  - export ORG=mfdz

install: true

services:
  - docker

jobs:
  include:
    - stage: test
      env: LINT,UNIT
      node_js: '10'
      script: yarn install && yarn lint && yarn test-coverage

#    - stage: visual
#      env: VISUAL=chrome
#      node_js: '10'
#      script: test/visual.sh

    - stage: build and deploy container
      node_js: '10'
      script: test/deploy.sh
