sudo: required

dist: bionic

branches:
  only:
    - master
    - next
    - next-prod
    - force-build
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

before_install:
  - export TZ=Europe/Helsinki

install: true

services:
  - docker

jobs:
  include:
    # - stage: test
    #   env: LINT=1
    #   node_js: '10'
    #   script:
    #     - rm -rf node_modules
    #     - yarn setup
    #     - yarn lint
    # Temporarely disabled for development in next branch
    # - stage: test
    #   env: FLOW=1
    #   node_js: '10'
    #   script:
    #     - yarn setup
    #     - test/flow.sh
    # - stage: test
    #   env: UNIT=1
    #   node_js: '10'
    #   script:
    #     - rm -rf node_modules
    #     - yarn setup
    #     - yarn relay
    #    - yarn run test-coverage
    #    - yarn run test-report

    - stage: build and deploy container
      node_js: '10'
      script: test/deploy.sh
